---
- hosts: all
  gather_facts: false
  tasks:
    - name: Configure hostname and domain name
      cisco.ios.ios_system:
      hostname: {{ hostname }}
      #domain_name: test.example.com
      #domain_search:
        #- ansible.com
        #- redhat.com
        #- cisco.com
      lookup_enabled: true

    #- name: configure top level configuration
    #  ios_config:
    #     lines: hostname {{ hostname }}