---
- name: Collect VLANs from Cisco Switch and Import into NetBox
  hosts: your_switch
  gather_facts: no
  tasks:
    - name: Collect VLAN information from the Cisco switch
      cisco.ios.ios_facts:
        gather_subset: vlan
      register: vlan_data

    - name: Loop through VLAN data and create VLANs in NetBox
      include_tasks: import_vlans.yml
      loop: "{{ vlan_data.ansible_facts.vlans }}"
      loop_control:
        loop_var: vlan

    - name: Display VLANs created in NetBox
      debug:
        var: netbox_vlan_result.results